// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 AIC Contributors

import type { FileContentReader } from "@jatbas/aic-shared/core/interfaces/file-content-reader.interface.js";
import type { RulePackProvider } from "@jatbas/aic-shared/core/interfaces/rule-pack-provider.interface.js";
import type { BudgetConfig } from "@jatbas/aic-shared/core/interfaces/budget-config.interface.js";
import type { HeuristicSelectorConfig } from "@jatbas/aic-shared/core/interfaces/heuristic-selector-config.interface.js";
import type { LanguageProvider } from "@jatbas/aic-shared/core/interfaces/language-provider.interface.js";
import type { PipelineStepsDeps } from "@jatbas/aic-shared/core/run-pipeline-steps.js";
import type { FileExtension } from "@jatbas/aic-shared/core/types/paths.js";
import type { TokenCount } from "@jatbas/aic-shared/core/types/units.js";
import { toFileExtension } from "@jatbas/aic-shared/core/types/paths.js";
import { IntentClassifier } from "@jatbas/aic-shared/pipeline/intent-classifier.js";
import { RulePackResolver } from "@jatbas/aic-shared/pipeline/rule-pack-resolver.js";
import { BudgetAllocator } from "@jatbas/aic-shared/pipeline/budget-allocator.js";
import { HeuristicSelector } from "@jatbas/aic-shared/pipeline/heuristic-selector.js";
import { ImportGraphProximityScorer } from "@jatbas/aic-shared/pipeline/import-graph-proximity-scorer.js";
import { SymbolRelevanceScorer } from "@jatbas/aic-shared/pipeline/symbol-relevance-scorer.js";
import { ExclusionScanner } from "@jatbas/aic-shared/pipeline/exclusion-scanner.js";
import { SecretScanner } from "@jatbas/aic-shared/pipeline/secret-scanner.js";
import { PromptInjectionScanner } from "@jatbas/aic-shared/pipeline/prompt-injection-scanner.js";
import { MarkdownInstructionScanner } from "@jatbas/aic-shared/pipeline/markdown-instruction-scanner.js";
import { CommandInjectionScanner } from "@jatbas/aic-shared/pipeline/command-injection-scanner.js";
import { ContextGuard } from "@jatbas/aic-shared/pipeline/context-guard.js";
import { Base64InlineDataStripper } from "@jatbas/aic-shared/pipeline/base64-inline-data-stripper.js";
import { LongStringLiteralTruncator } from "@jatbas/aic-shared/pipeline/long-string-literal-truncator.js";
import { DocstringTrimmer } from "@jatbas/aic-shared/pipeline/docstring-trimmer.js";
import { ImportDeduplicator } from "@jatbas/aic-shared/pipeline/import-deduplicator.js";
import { LicenseHeaderStripper } from "@jatbas/aic-shared/pipeline/license-header-stripper.js";
import { WhitespaceNormalizer } from "@jatbas/aic-shared/pipeline/whitespace-normalizer.js";
import { TestStructureExtractor } from "@jatbas/aic-shared/pipeline/test-structure-extractor.js";
import { CommentStripper } from "@jatbas/aic-shared/pipeline/comment-stripper.js";
import { JsonCompactor } from "@jatbas/aic-shared/pipeline/json-compactor.js";
import { LockFileSkipper } from "@jatbas/aic-shared/pipeline/lock-file-skipper.js";
import { MinifiedCodeSkipper } from "@jatbas/aic-shared/pipeline/minified-code-skipper.js";
import { AutoGeneratedSkipper } from "@jatbas/aic-shared/pipeline/auto-generated-skipper.js";
import { EnvExampleRedactor } from "@jatbas/aic-shared/pipeline/env-example-redactor.js";
import { SchemaFileCompactor } from "@jatbas/aic-shared/pipeline/schema-file-compactor.js";
import { HtmlToMarkdownTransformer } from "@jatbas/aic-shared/pipeline/html-to-markdown-transformer.js";
import { YamlCompactor } from "@jatbas/aic-shared/pipeline/yaml-compactor.js";
import { SvgDescriber } from "@jatbas/aic-shared/pipeline/svg-describer.js";
import { CssVariableSummarizer } from "@jatbas/aic-shared/pipeline/css-variable-summarizer.js";
import { TypeDeclarationCompactor } from "@jatbas/aic-shared/pipeline/type-declaration-compactor.js";
import { ContentTransformerPipeline } from "@jatbas/aic-shared/pipeline/content-transformer-pipeline.js";
import { SummarisationLadder } from "@jatbas/aic-shared/pipeline/summarisation-ladder.js";
import { LineLevelPruner } from "@jatbas/aic-shared/pipeline/line-level-pruner.js";
import { PromptAssembler } from "@jatbas/aic-shared/pipeline/prompt-assembler.js";
import { StructuralMapBuilder } from "@jatbas/aic-shared/pipeline/structural-map-builder.js";
import { IntentAwareFileDiscoverer } from "@jatbas/aic-shared/pipeline/intent-aware-file-discoverer.js";
import { SpecFileDiscoverer } from "@jatbas/aic-shared/pipeline/spec-file-discoverer.js";
import { ConversationCompressorImpl } from "@jatbas/aic-shared/pipeline/conversation-compressor.js";
import { TiktokenAdapter } from "@jatbas/aic-shared/adapters/tiktoken-adapter.js";
import { TypeScriptProvider } from "@jatbas/aic-shared/adapters/typescript-provider.js";
import { MarkdownProvider } from "@jatbas/aic-shared/adapters/markdown-provider.js";
import { GenericImportProvider } from "@jatbas/aic-shared/adapters/generic-import-provider.js";
import { GenericProvider } from "@jatbas/aic-shared/adapters/generic-provider.js";
import { FastGlobAdapter } from "@jatbas/aic-shared/adapters/fast-glob-adapter.js";
import { IgnoreAdapter } from "@jatbas/aic-shared/adapters/ignore-adapter.js";
import { FileSystemRepoMapSupplier } from "@jatbas/aic-shared/adapters/file-system-repo-map-supplier.js";
import { WatchingRepoMapSupplier } from "@jatbas/aic-shared/adapters/watching-repo-map-supplier.js";

export type PipelineDepsWithoutRepoMap = Omit<PipelineStepsDeps, "repoMapSupplier">;

const WHITESPACE_EXCLUDED_EXTENSIONS: readonly FileExtension[] = [
  toFileExtension(".md"),
  toFileExtension(".mdx"),
  toFileExtension(".py"),
  toFileExtension(".yml"),
  toFileExtension(".yaml"),
];

export function createPipelineDeps(
  fileContentReader: FileContentReader,
  rulePackProvider: RulePackProvider,
  budgetConfig: BudgetConfig,
  additionalProviders?: readonly LanguageProvider[],
  heuristicSelectorConfig?: HeuristicSelectorConfig,
): PipelineDepsWithoutRepoMap {
  const tiktokenAdapter = new TiktokenAdapter();
  const tokenCounter = (text: string): TokenCount => tiktokenAdapter.countTokens(text);
  const typeScriptProvider = new TypeScriptProvider();
  const markdownProvider = new MarkdownProvider();
  const genericImportProvider = new GenericImportProvider();
  const genericProvider = new GenericProvider();
  const languageProviders = [
    typeScriptProvider,
    markdownProvider,
    ...(additionalProviders ?? []),
    genericImportProvider,
    genericProvider,
  ] as const;
  const intentClassifier = new IntentClassifier();
  const rulePackResolver = new RulePackResolver(rulePackProvider);
  const budgetAllocator = new BudgetAllocator(budgetConfig);
  const importProximityScorer = new ImportGraphProximityScorer(
    fileContentReader,
    languageProviders,
  );
  const symbolRelevanceScorer = new SymbolRelevanceScorer(
    fileContentReader,
    languageProviders,
  );
  const heuristicSelector = new HeuristicSelector(
    languageProviders,
    heuristicSelectorConfig ?? { maxFiles: 20 },
    importProximityScorer,
    symbolRelevanceScorer,
  );
  const exclusionScanner = new ExclusionScanner();
  const secretScanner = new SecretScanner();
  const promptInjectionScanner = new PromptInjectionScanner();
  const markdownInstructionScanner = new MarkdownInstructionScanner();
  const commandInjectionScanner = new CommandInjectionScanner();
  const scanners = [
    exclusionScanner,
    secretScanner,
    promptInjectionScanner,
    markdownInstructionScanner,
    commandInjectionScanner,
  ] as const;
  const contextGuard = new ContextGuard(scanners, fileContentReader, []);
  const whitespaceNormalizer = new WhitespaceNormalizer(WHITESPACE_EXCLUDED_EXTENSIONS);
  const testStructureExtractor = new TestStructureExtractor();
  const commentStripper = new CommentStripper();
  const jsonCompactor = new JsonCompactor();
  const lockFileSkipper = new LockFileSkipper();
  const minifiedCodeSkipper = new MinifiedCodeSkipper();
  const autoGeneratedSkipper = new AutoGeneratedSkipper();
  const envExampleRedactor = new EnvExampleRedactor();
  const schemaFileCompactor = new SchemaFileCompactor();
  const htmlToMarkdownTransformer = new HtmlToMarkdownTransformer();
  const yamlCompactor = new YamlCompactor();
  const svgDescriber = new SvgDescriber();
  const cssVariableSummarizer = new CssVariableSummarizer();
  const typeDeclarationCompactor = new TypeDeclarationCompactor();
  const licenseHeaderStripper = new LicenseHeaderStripper();
  const base64InlineDataStripper = new Base64InlineDataStripper();
  const longStringLiteralTruncator = new LongStringLiteralTruncator();
  const docstringTrimmer = new DocstringTrimmer();
  const importDeduplicator = new ImportDeduplicator();
  const transformers = [
    licenseHeaderStripper,
    base64InlineDataStripper,
    longStringLiteralTruncator,
    docstringTrimmer,
    importDeduplicator,
    whitespaceNormalizer,
    testStructureExtractor,
    commentStripper,
    jsonCompactor,
    lockFileSkipper,
    minifiedCodeSkipper,
    autoGeneratedSkipper,
    envExampleRedactor,
    schemaFileCompactor,
    htmlToMarkdownTransformer,
    yamlCompactor,
    svgDescriber,
    cssVariableSummarizer,
    typeDeclarationCompactor,
  ] as const;
  const contentTransformerPipeline = new ContentTransformerPipeline(
    transformers,
    fileContentReader,
    tokenCounter,
  );
  const summarisationLadder = new SummarisationLadder(
    languageProviders,
    tokenCounter,
    fileContentReader,
  );
  const lineLevelPruner = new LineLevelPruner(tiktokenAdapter, fileContentReader);
  const promptAssembler = new PromptAssembler(fileContentReader);
  const structuralMapBuilder = new StructuralMapBuilder();
  const intentAwareFileDiscoverer = new IntentAwareFileDiscoverer();
  const specFileDiscoverer = new SpecFileDiscoverer();
  const conversationCompressor = new ConversationCompressorImpl();
  return {
    intentClassifier,
    rulePackResolver,
    budgetAllocator,
    contextSelector: heuristicSelector,
    contextGuard,
    contentTransformerPipeline,
    summarisationLadder,
    lineLevelPruner,
    promptAssembler,
    structuralMapBuilder,
    intentAwareFileDiscoverer,
    tokenCounter: tiktokenAdapter,
    specFileDiscoverer,
    conversationCompressor,
  };
}

export function createFullPipelineDeps(
  fileContentReader: FileContentReader,
  rulePackProvider: RulePackProvider,
  budgetConfig: BudgetConfig,
  additionalProviders?: readonly LanguageProvider[],
  heuristicSelectorConfig?: HeuristicSelectorConfig,
): PipelineStepsDeps {
  const partial = createPipelineDeps(
    fileContentReader,
    rulePackProvider,
    budgetConfig,
    additionalProviders,
    heuristicSelectorConfig,
  );
  const ignoreAdapter = new IgnoreAdapter();
  const inner = new FileSystemRepoMapSupplier(new FastGlobAdapter(), ignoreAdapter);
  const repoMapSupplier = new WatchingRepoMapSupplier(inner, ignoreAdapter);
  return { ...partial, repoMapSupplier };
}
