module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "feat",
        "fix",
        "docs",
        "chore",
        "refactor",
        "perf",
        "test",
        "style",
        "ci",
        "build",
        "revert",
      ],
    ],
    "subject-max-length": [2, "always", 72],
    "subject-case": [0],
    "subject-full-stop": [2, "never", "."],
    "header-max-length": [2, "always", 72],
    "body-max-length": [2, "always", 0],
    "body-max-line-length": [2, "always", 0],
    "footer-max-length": [2, "always", 0],
    "footer-max-line-length": [2, "always", 0],
  },
};
