import { describe, it, expect } from "vitest";
import { AutoGeneratedSkipper } from "../auto-generated-skipper.js";
import { toRelativePath } from "#core/types/paths.js";
import { INCLUSION_TIER } from "#core/types/enums.js";

describe("AutoGeneratedSkipper", () => {
  it("code_generated_comment_returns_placeholder", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("gen/file.ts");
    const content =
      "// Code generated by protoc.\n// source: foo.proto\nconst x = 1;";
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toBe("[Auto-generated: file.ts — skipped]");
  });

  it("hash_auto_generated_returns_placeholder", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("src/api.py");
    const content =
      "# AUTO-GENERATED\n# Do not edit.\ndef f(): pass";
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toContain("[Auto-generated:");
    expect(result).toContain("— skipped]");
  });

  it("no_marker_returns_unchanged", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("src/index.ts");
    const content = "export const x = 1;";
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toBe(content);
  });

  it("empty_content_returns_unchanged", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("src/foo.js");
    const content = "";
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toBe("");
  });

  it("marker_beyond_header_unchanged", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("src/bar.ts");
    const first30 = Array.from({ length: 30 }, () => "// comment").join("\n");
    const content = `${first30}\n// Code generated`;
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toBe(content);
  });

  it("safety_python_indentation_preserved", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("src/main.py");
    const content = "def f():\n  pass";
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toBe(content);
  });

  it("safety_yaml_structure_unchanged", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("config.yml");
    const content = "key:\n  nested: 1";
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toBe(content);
  });

  it("safety_jsx_structure_unchanged", () => {
    const transformer = new AutoGeneratedSkipper();
    const filePath = toRelativePath("src/App.tsx");
    const content = "<div>x</div>";
    const result = transformer.transform(
      content,
      INCLUSION_TIER.L0,
      filePath,
    );
    expect(result).toBe(content);
  });
});
