// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2025 AIC Contributors

import type { ContentTransformer } from "@jatbas/aic-core/core/interfaces/content-transformer.interface.js";
import type { FileExtension, RelativePath } from "@jatbas/aic-core/core/types/paths.js";
import type { InclusionTier } from "@jatbas/aic-core/core/types/enums.js";

const HEADER_MAX_LINES = 30;
const HEADER_MAX_CHARS = 2048;

const EMPTY_EXTENSIONS: readonly FileExtension[] = [];

function getHeaderRegion(content: string): string {
  const lines = content.split("\n");
  const firstLines = lines.slice(0, HEADER_MAX_LINES).join("\n");
  const firstChars = content.slice(0, HEADER_MAX_CHARS);
  return firstLines.length <= firstChars.length ? firstLines : firstChars;
}

function hasAutoGeneratedHeader(content: string): boolean {
  const region = getHeaderRegion(content);
  const lower1 = "code generated";
  const lower2 = "auto-generated";
  const lines = region.split("\n");
  return lines.some(
    (line) =>
      line.trim().toLowerCase().includes(lower1) ||
      line.trim().toLowerCase().includes(lower2),
  );
}

function lastSegment(path: RelativePath): string {
  const segments = path.split("/");
  return segments.length > 0 ? (segments[segments.length - 1] ?? path) : path;
}

export class AutoGeneratedSkipper implements ContentTransformer {
  readonly id = "auto-generated-skipper";
  readonly fileExtensions: readonly FileExtension[] = EMPTY_EXTENSIONS;

  transform(content: string, _tier: InclusionTier, filePath: RelativePath): string {
    if (content.length === 0) return content;
    if (!hasAutoGeneratedHeader(content)) return content;
    const name = lastSegment(filePath);
    return `[Auto-generated: ${name} — skipped]`;
  }
}
